// Demo data for when APIs are not configured

export const demoAffiliates = [
  {
    id: "demo-1",
    name: "Carlos Martínez",
    email: "carlos@example.com",
    code: "CARLOS20",
    discount_percent: 20,
    commission_percent: 15,
    referral_link: "https://tienda.lactatepro.com?ref=carlos",
    status: "active",
    total_sales: 12450.00,
    total_commission: 1867.50,
    created_at: "2024-01-15",
  },
  {
    id: "demo-2",
    name: "María López",
    email: "maria@example.com",
    code: "MARIA15",
    discount_percent: 15,
    commission_percent: 12,
    referral_link: "https://tienda.lactatepro.com?ref=maria",
    status: "active",
    total_sales: 8320.00,
    total_commission: 998.40,
    created_at: "2024-02-20",
  },
  {
    id: "demo-3",
    name: "Juan García",
    email: "juan@example.com",
    code: "JUAN10",
    discount_percent: 10,
    commission_percent: 10,
    referral_link: "https://tienda.lactatepro.com?ref=juan",
    status: "active",
    total_sales: 5670.00,
    total_commission: 567.00,
    created_at: "2024-03-10",
  },
  {
    id: "demo-4",
    name: "Ana Rodríguez",
    email: "ana@example.com",
    code: "ANA25",
    discount_percent: 25,
    commission_percent: 18,
    referral_link: "https://tienda.lactatepro.com?ref=ana",
    status: "inactive",
    total_sales: 3200.00,
    total_commission: 576.00,
    created_at: "2024-01-05",
  },
]

export const demoTasks = [
  {
    id: "task-1",
    title: "Revisar inventario de Lactate Pro 2",
    description: "Verificar stock actual y hacer pedido si es necesario",
    status: "pending",
    priority: "high",
    due_date: "2026-04-16",
    assigned_to: "Oriol",
    created_at: "2026-04-01",
  },
  {
    id: "task-2",
    title: "Contactar nuevos influencers",
    description: "Enviar propuesta de afiliacion a 5 nuevos atletas",
    status: "in_progress",
    priority: "medium",
    due_date: "2026-04-20",
    assigned_to: "Carlos",
    created_at: "2026-04-05",
  },
  {
    id: "task-3",
    title: "Actualizar precios de temporada",
    description: "Aplicar descuentos de primavera en Shopify",
    status: "completed",
    priority: "high",
    due_date: "2026-04-10",
    assigned_to: "Hector",
    created_at: "2026-04-01",
  },
  {
    id: "task-4",
    title: "Crear contenido para redes",
    description: "Preparar posts sobre beneficios del medidor de lactato",
    status: "pending",
    priority: "low",
    due_date: "2026-04-25",
    assigned_to: "Ale",
    created_at: "2026-04-08",
  },
]

export const demoSales = [
  { month: "Ene", ventas: 4200, comisiones: 630 },
  { month: "Feb", ventas: 5100, comisiones: 765 },
  { month: "Mar", ventas: 4800, comisiones: 720 },
  { month: "Abr", ventas: 6200, comisiones: 930 },
  { month: "May", ventas: 7500, comisiones: 1125 },
  { month: "Jun", ventas: 8900, comisiones: 1335 },
]

export const demoShopifyOrders = [
  {
    id: "5001",
    order_number: "#5001",
    customer: "Pedro Sánchez",
    email: "pedro@email.com",
    total: 149.99,
    status: "fulfilled",
    created_at: "2024-04-08",
    items: 2,
  },
  {
    id: "5002",
    order_number: "#5002",
    customer: "Laura Gómez",
    email: "laura@email.com",
    total: 299.99,
    status: "pending",
    created_at: "2024-04-09",
    items: 1,
  },
  {
    id: "5003",
    order_number: "#5003",
    customer: "Miguel Torres",
    email: "miguel@email.com",
    total: 449.99,
    status: "fulfilled",
    created_at: "2024-04-07",
    items: 3,
  },
]

export const demoProducts = [
  {
    id: "prod-1",
    title: "Lactate Pro 2 LT-1730",
    price: 299.99,
    inventory: 45,
    status: "active",
    image: null,
  },
  {
    id: "prod-2",
    title: "Tiras de Test Lactate (25 uds)",
    price: 49.99,
    inventory: 120,
    status: "active",
    image: null,
  },
  {
    id: "prod-3",
    title: "Kit Completo Entrenamiento",
    price: 449.99,
    inventory: 15,
    status: "active",
    image: null,
  },
]

export const demoStats = {
  totalSales: 29640.00,
  activeAffiliates: 3,
  pendingCommissions: 4008.90,
  pendingTasks: 2,
}

export const demoCommissions = [
  {
    id: "comm-1",
    affiliate_id: "demo-1",
    affiliate_name: "Carlos Martínez",
    order_id: "#5001",
    sale_amount: 149.99,
    commission_amount: 22.50,
    status: "pending",
    created_at: "2024-04-08",
  },
  {
    id: "comm-2",
    affiliate_id: "demo-2",
    affiliate_name: "María López",
    order_id: "#5003",
    sale_amount: 449.99,
    commission_amount: 54.00,
    status: "paid",
    created_at: "2024-04-07",
  },
  {
    id: "comm-3",
    affiliate_id: "demo-1",
    affiliate_name: "Carlos Martínez",
    order_id: "#4998",
    sale_amount: 299.99,
    commission_amount: 45.00,
    status: "pending",
    created_at: "2024-04-05",
  },
]
