// Demo data for when APIs are not configured

export const demoAffiliates = [
  {
    id: "demo-1",
    name: "Carlos Martínez",
    email: "carlos@example.com",
    code: "CARLOS20",
    discount_percent: 20,
    commission_percent: 15,
    referral_link: "https://tienda.lactatepro.com?ref=carlos",
    status: "active",
    total_sales: 12450.00,
    total_commission: 1867.50,
    created_at: "2024-01-15",
  },
  {
    id: "demo-2",
    name: "María López",
    email: "maria@example.com",
    code: "MARIA15",
    discount_percent: 15,
    commission_percent: 12,
    referral_link: "https://tienda.lactatepro.com?ref=maria",
    status: "active",
    total_sales: 8320.00,
    total_commission: 998.40,
    created_at: "2024-02-20",
  },
  {
    id: "demo-3",
    name: "Juan García",
    email: "juan@example.com",
    code: "JUAN10",
    discount_percent: 10,
    commission_percent: 10,
    referral_link: "https://tienda.lactatepro.com?ref=juan",
    status: "active",
    total_sales: 5670.00,
    total_commission: 567.00,
    created_at: "2024-03-10",
  },
  {
    id: "demo-4",
    name: "Ana Rodríguez",
    email: "ana@example.com",
    code: "ANA25",
    discount_percent: 25,
    commission_percent: 18,
    referral_link: "https://tienda.lactatepro.com?ref=ana",
    status: "inactive",
    total_sales: 3200.00,
    total_commission: 576.00,
    created_at: "2024-01-05",
  },
]

export const demoTasks = [
  {
    id: "task-1",
    title: "Revisar inventario de Lactate Pro 2",
    description: "Verificar stock actual y hacer pedido si es necesario",
    status: "pending",
    priority: "high",
    due_date: "2026-04-16",
    assigned_to: "Oriol",
    created_at: "2026-04-01",
  },
  {
    id: "task-2",
    title: "Contactar nuevos influencers",
    description: "Enviar propuesta de afiliacion a 5 nuevos atletas",
    status: "in_progress",
    priority: "medium",
    due_date: "2026-04-20",
    assigned_to: "Carlos",
    created_at: "2026-04-05",
  },
  {
    id: "task-3",
    title: "Actualizar precios de temporada",
    description: "Aplicar descuentos de primavera en Shopify",
    status: "completed",
    priority: "high",
    due_date: "2026-04-10",
    assigned_to: "Hector",
    created_at: "2026-04-01",
  },
  {
    id: "task-4",
    title: "Crear contenido para redes",
    description: "Preparar posts sobre beneficios del medidor de lactato",
    status: "pending",
    priority: "low",
    due_date: "2026-04-25",
    assigned_to: "Ale",
    created_at: "2026-04-08",
  },
]

export const demoSales = [
  { month: "Ene", ventas: 4200, comisiones: 630 },
  { month: "Feb", ventas: 5100, comisiones: 765 },
  { month: "Mar", ventas: 4800, comisiones: 720 },
  { month: "Abr", ventas: 6200, comisiones: 930 },
  { month: "May", ventas: 7500, comisiones: 1125 },
  { month: "Jun", ventas: 8900, comisiones: 1335 },
]

export const demoShopifyOrders = [
  {
    id: "5001",
    order_number: "#5001",
    customer: "Pedro Sánchez",
    email: "pedro@email.com",
    total: 149.99,
    status: "fulfilled",
    created_at: "2024-04-08",
    items: 2,
  },
  {
    id: "5002",
    order_number: "#5002",
    customer: "Laura Gómez",
    email: "laura@email.com",
    total: 299.99,
    status: "pending",
    created_at: "2024-04-09",
    items: 1,
  },
  {
    id: "5003",
    order_number: "#5003",
    customer: "Miguel Torres",
    email: "miguel@email.com",
    total: 449.99,
    status: "fulfilled",
    created_at: "2024-04-07",
    items: 3,
  },
]

export const demoProducts = [
  {
    id: "prod-1",
    title: "Lactate Pro 2 LT-1730",
    price: 299.99,
    inventory: 45,
    status: "active",
    image: null,
  },
  {
    id: "prod-2",
    title: "Tiras de Test Lactate (25 uds)",
    price: 49.99,
    inventory: 120,
    status: "active",
    image: null,
  },
  {
    id: "prod-3",
    title: "Kit Completo Entrenamiento",
    price: 449.99,
    inventory: 15,
    status: "active",
    image: null,
  },
]

export const demoStats = {
  totalSales: 29640.00,
  activeAffiliates: 3,
  pendingCommissions: 4008.90,
  pendingTasks: 2,
}

export const demoClients = [
  {
    id: "client-1",
    name: "Universidad San Sebastián",
    rut: "71.631.900-8",
    address: "General Lagos 1163, Valdivia",
    phone: "950672154",
    contact_person: "Carmen Sayago De Arevalo",
    email: "Carmen.Sayago@uss.cl",
    notes: "Cliente recurrente - departamento de kinesiología",
    created_at: "2026-01-15",
  },
  {
    id: "client-2",
    name: "Club Deportivo UC",
    rut: "65.432.100-5",
    address: "Av. Libertador Bernardo O'Higgins 340, Santiago",
    phone: "912345678",
    contact_person: "Roberto Méndez",
    email: "roberto@clubuc.cl",
    notes: "",
    created_at: "2026-02-20",
  },
  {
    id: "client-3",
    name: "Centro Médico Deportivo Vitacura",
    rut: "76.543.210-K",
    address: "Av. Vitacura 5250, Vitacura, Santiago",
    phone: "223456789",
    contact_person: "Dra. Alejandra Ruiz",
    email: "aruiz@cmdvitacura.cl",
    notes: "Pago a 30 días",
    created_at: "2026-03-10",
  },
]

export const demoCatalogProducts = [
  {
    id: "cprod-1",
    name: "Eaglenos Lactato Cintas",
    description: "Tiras reactivas para medición de lactato",
    price: 79990,
    stock: 200,
    sku: "EAG-LAC-001",
  },
  {
    id: "cprod-2",
    name: "Maquina de Lactato",
    description: "Dispositivo portátil para medición de lactato en sangre",
    price: 189990,
    stock: 15,
    sku: "MAQ-LAC-001",
  },
  {
    id: "cprod-3",
    name: "Eaglenos Cintas de Glucosa",
    description: "Tiras reactivas para medición de glucosa",
    price: 19990,
    stock: 150,
    sku: "EAG-GLU-001",
  },
  {
    id: "cprod-4",
    name: "Kit Completo Lactato Pro",
    description: "Incluye máquina + 50 cintas de lactato",
    price: 349990,
    stock: 8,
    sku: "KIT-LAC-001",
  },
]

export const demoInvoices = [
  {
    id: "inv-1",
    client_id: "client-1",
    client_name: "Universidad San Sebastián",
    invoice_number: "COT-2026-001",
    type: "cotizacion" as const,
    status: "sent" as const,
    issue_date: "2026-04-21",
    validity_days: 30,
    subtotal: 1789790,
    tax_rate: 19,
    tax_amount: 340060,
    total: 2129850,
    is_recurring: false,
    recurring_frequency: null,
    notes: "",
    created_at: "2026-04-21",
    items: [
      { description: "Eaglenos Lactato Cintas", quantity: 20, unit_price: 79990, amount: 1599800 },
      { description: "Maquina de Lactato", quantity: 1, unit_price: 189990, amount: 189990 },
      { description: "Eaglenos Cintas de Glucosa", quantity: 0, unit_price: 19990, amount: 0 },
    ],
  },
  {
    id: "inv-2",
    client_id: "client-2",
    client_name: "Club Deportivo UC",
    invoice_number: "FAC-2026-001",
    type: "factura" as const,
    status: "paid" as const,
    issue_date: "2026-03-15",
    validity_days: 30,
    subtotal: 349990,
    tax_rate: 19,
    tax_amount: 66498,
    total: 416488,
    is_recurring: false,
    recurring_frequency: null,
    notes: "",
    created_at: "2026-03-15",
    items: [
      { description: "Kit Completo Lactato Pro", quantity: 1, unit_price: 349990, amount: 349990 },
    ],
  },
  {
    id: "inv-3",
    client_id: "client-3",
    client_name: "Centro Médico Deportivo Vitacura",
    invoice_number: "FAC-2026-002",
    type: "factura" as const,
    status: "overdue" as const,
    issue_date: "2026-02-10",
    validity_days: 30,
    subtotal: 399950,
    tax_rate: 19,
    tax_amount: 75990,
    total: 475940,
    is_recurring: true,
    recurring_frequency: "monthly" as const,
    notes: "Suministro mensual de cintas",
    created_at: "2026-02-10",
    items: [
      { description: "Eaglenos Lactato Cintas", quantity: 5, unit_price: 79990, amount: 399950 },
    ],
  },
]

export const demoClientActivities = [
  {
    id: "act-1",
    client_id: "client-1",
    invoice_id: "inv-1",
    type: "invoice_created",
    title: "Cotización COT-2026-001 creada",
    description: "Cotización por $2.129.850 — 20x Eaglenos Lactato Cintas + 1x Maquina de Lactato",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-04-21T10:00:00Z",
  },
  {
    id: "act-2",
    client_id: "client-1",
    invoice_id: "inv-1",
    type: "email_sent",
    title: "Cotización enviada por email",
    description: "Enviada a Carmen.Sayago@uss.cl con PDF adjunto",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-04-21T11:30:00Z",
  },
  {
    id: "act-3",
    client_id: "client-1",
    invoice_id: null,
    type: "note",
    title: "Llamada de seguimiento",
    description: "Carmen confirma que están revisando la cotización con el departamento de compras. Esperan aprobar esta semana.",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-04-23T15:00:00Z",
  },
  {
    id: "act-4",
    client_id: "client-1",
    invoice_id: "inv-1",
    type: "payment_reminder",
    title: "Recordatorio: seguimiento de pago",
    description: "Enviar email de seguimiento si no confirman el pago esta semana",
    is_reminder: true,
    reminder_date: "2026-04-28",
    reminder_completed: false,
    created_at: "2026-04-23T15:05:00Z",
  },
  {
    id: "act-5",
    client_id: "client-2",
    invoice_id: "inv-2",
    type: "invoice_created",
    title: "Factura FAC-2026-001 creada",
    description: "Factura por $416.488 — 1x Kit Completo Lactato Pro",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-03-15T09:00:00Z",
  },
  {
    id: "act-6",
    client_id: "client-2",
    invoice_id: "inv-2",
    type: "invoice_paid",
    title: "Factura FAC-2026-001 pagada",
    description: "Pago recibido por transferencia bancaria",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-03-22T14:00:00Z",
  },
  {
    id: "act-7",
    client_id: "client-3",
    invoice_id: "inv-3",
    type: "invoice_created",
    title: "Factura FAC-2026-002 creada",
    description: "Factura recurrente mensual por $475.940 — 5x Eaglenos Lactato Cintas",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "act-8",
    client_id: "client-3",
    invoice_id: "inv-3",
    type: "invoice_overdue",
    title: "Factura FAC-2026-002 vencida",
    description: "Han pasado 30 días sin recibir pago. Contactar al cliente.",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-03-12T08:00:00Z",
  },
  {
    id: "act-9",
    client_id: "client-3",
    invoice_id: null,
    type: "email_reminder",
    title: "Recordatorio: enviar email de cobro",
    description: "Enviar segundo aviso de pago pendiente a Dra. Alejandra Ruiz",
    is_reminder: true,
    reminder_date: "2026-04-26",
    reminder_completed: false,
    created_at: "2026-04-20T09:00:00Z",
  },
  {
    id: "act-10",
    client_id: "client-2",
    invoice_id: null,
    type: "call",
    title: "Llamada con Roberto Méndez",
    description: "Interesados en comprar más cintas para la pretemporada. Enviar nueva cotización.",
    is_reminder: false,
    reminder_date: null,
    reminder_completed: false,
    created_at: "2026-04-18T11:00:00Z",
  },
]

export const demoCommissions = [
  {
    id: "comm-1",
    affiliate_id: "demo-1",
    affiliate_name: "Carlos Martínez",
    order_id: "#5001",
    sale_amount: 149.99,
    commission_amount: 22.50,
    status: "pending",
    created_at: "2024-04-08",
  },
  {
    id: "comm-2",
    affiliate_id: "demo-2",
    affiliate_name: "María López",
    order_id: "#5003",
    sale_amount: 449.99,
    commission_amount: 54.00,
    status: "paid",
    created_at: "2024-04-07",
  },
  {
    id: "comm-3",
    affiliate_id: "demo-1",
    affiliate_name: "Carlos Martínez",
    order_id: "#4998",
    sale_amount: 299.99,
    commission_amount: 45.00,
    status: "pending",
    created_at: "2024-04-05",
  },
]
